image: gcr.io/pi-dev-sandbox/gitlab-ci-base:jessie

variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  GIT_DEPTH: 10

services:
  - docker:19.03.1-dind

stages:
  - build-test-php7
  - test-php7
  - build-test-php7-2
  - test-php7-2
  - package
  - build
  - deploy

#########################
####  TEMPLATE      ####
########################

.before_template: &before_template
  before_script:
    - sed -i -e "s/{HIPAY_API_USER_TEST\}/$HIPAY_API_USER_TEST/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s/{HIPAY_API_PASSWORD_TEST\}/$HIPAY_API_PASSWORD_TEST/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s/{HIPAY_TOKENJS_PUBLICKEY_TEST\}/$HIPAY_TOKENJS_PUBLICKEY_TEST/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s/{HIPAY_TOKENJS_USERNAME_TEST\}/$HIPAY_TOKENJS_USERNAME_TEST/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s/{HIPAY_SECRET_PASSPHRASE_TEST\}/$HIPAY_SECRET_PASSPHRASE_TEST/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s/{HIPAY_API_USER_TEST_MOTO\}/$HIPAY_API_USER_RE7/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s/{HIPAY_API_PASSWORD_TEST_MOTO\}/$HIPAY_API_PASSWORD_RE7/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s/{HIPAY_SECRET_PASSPHRASE_TEST_MOTO\}/$HIPAY_SECRET_PASSPHRASE_RE7/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s@{PI_CI_DATA_URL\}@$PI_CI_DATA_URL@" ./bin/docker/conf/test/hipay.env.sample
    - sh bin/docker/generate_dockerfile.sh
  artifacts:
    paths:
      - bin/tests/errors
      - bin/tests/tests-cypress/cypress/videos
      - bin/tests/tests-cypress/cypress/screenshots
    when: always

#########################################################################
###                                PHP 7-1                            ###
#########################################################################
build-test:
  stage: build-test-php7
  script:
    - sh bin/docker/generate_dockerfile.sh
    - sh ./bin/docker/init-environment.sh php7.1
  tags:
    - gcp-default-runner
  allow_failure: false
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-tests/

casperjs-part1-1:
  stage: test-php7
  <<: *before_template
  script:
    - sh ./bin/gitlab/create-env.sh docker-compose.test.yml
    - sh ./bin/gitlab/run-tests.sh 0
  retry: 2
  tags:
    - gcp-cypress-runner
  allow_failure: true
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-tests/

casperjs-part2-1:
  stage: test-php7
  <<: *before_template
  script:
    - sh ./bin/gitlab/create-env.sh docker-compose.test.yml
    - sh ./bin/gitlab/run-tests.sh 1
  retry: 2
  tags:
    - gcp-cypress-runner
  allow_failure: true
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-tests/

casperjs-part3-1:
  stage: test-php7
  <<: *before_template
  script:
    - sh ./bin/gitlab/create-env.sh docker-compose.test.yml
    - sh ./bin/gitlab/run-tests.sh  2
  retry: 2
  tags:
    - gcp-cypress-runner
  allow_failure: true
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-tests/

casperjs-part4-1:
  stage: test-php7
  <<: *before_template
  script:
    - sh ./bin/gitlab/create-env.sh docker-compose.test.yml
    - sh ./bin/gitlab/run-tests.sh 3
  retry: 2
  tags:
    - gcp-cypress-runner
  allow_failure: true
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-tests/

test-cypress-5-1:
  stage: test-php7
  <<: *before_template
  script:
    - sh ./bin/gitlab/create-env.sh docker-compose.test.yml
    - sh ./bin/gitlab/run-cypress-tests.sh
  retry: 2
  tags:
    - gcp-cypress-runner
  allow_failure: true
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-tests/

#########################################################################
###                                PHP 7-2                            ###
#########################################################################

build-test-php-7-2:
  stage: build-test-php7-2
  script:
    - sh bin/docker/generate_dockerfile.sh
    - sh ./bin/docker/init-environment.sh php7-2
  tags:
    - gcp-default-runner
  allow_failure: false
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-tests/


casperjs-part1-3:
  stage: test-php7-2
  <<: *before_template
  script:
    - sh ./bin/gitlab/create-env.sh docker-compose.test-php7-2.yml
    - sh ./bin/gitlab/run-tests.sh 0
  retry: 2
  tags:
    - gcp-cypress-runner
  allow_failure: true
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-tests/

casperjs-part2-3:
  stage: test-php7-2
  <<: *before_template
  script:
    - sh ./bin/gitlab/create-env.sh docker-compose.test-php7-2.yml
    - sh ./bin/gitlab/run-tests.sh 1
  retry: 2
  tags:
    - gcp-cypress-runner
  allow_failure: true
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-tests/

casperjs-part3-3:
  stage: test-php7-2
  <<: *before_template
  script:
    - sh ./bin/gitlab/create-env.sh docker-compose.test-php7-2.yml
    - sh ./bin/gitlab/run-tests.sh 2
  retry: 2
  tags:
    - gcp-cypress-runner
  allow_failure: true
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-tests/

casperjs-part4-3:
  stage: test-php7-2
  <<: *before_template
  script:
    - sh ./bin/gitlab/create-env.sh docker-compose.test-php7-2.yml
    - sh ./bin/gitlab/run-tests.sh 3
  retry: 2
  tags:
    - gcp-cypress-runner
  allow_failure: true
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-tests/

test-cypress-5-3:
  stage: test-php7-2
  <<: *before_template
  script:
    - sh ./bin/gitlab/create-env.sh docker-compose.test-php7-2.yml
    - sh ./bin/gitlab/run-cypress-tests.sh
  retry: 2
  tags:
    - gcp-cypress-runner
  allow_failure: true
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-tests/

package:
  stage: package
  before_script:
    - apt-get update
    - apt-get install -y zip php5 libapache2-mod-php5
  script:
    - echo " Package module $CI_COMMIT_REF_SLUG"
    - cd src/lib/Hipay && composer install && cd ../../..
    - rm -Rf ./vendor && cp ./composer.json.dist ./composer.json && composer install &&  sh ./bin/deployment/packaging.sh
    - mkdir $CI_COMMIT_REF_SLUG
    - mkdir $CI_COMMIT_REF_SLUG/package
    - cp ./dist/*.tgz $CI_COMMIT_REF_SLUG/package/Allopass_Hipay-${CI_COMMIT_REF_SLUG}.tgz
  tags:
    - gcp-default-runner
  artifacts:
    paths:
      - ./dist

build:
  stage: build
  when: manual
  script:
    - docker-compose -f docker-compose.acceptance.yml build
    - docker-compose -f docker-compose.acceptance.yml push
    - docker rmi ${REGISTRY_URL}/${DOCKER_STACK}-${DOCKER_SERVICE}_web:${CI_COMMIT_REF_SLUG}
  tags:
    - pi-commerce-no-overlay


deploy2Recette:
  stage: deploy
  script:
    - echo "Deploy from registry"
    # Substitute env variables which dont exists on the distant machine
    - sed -i -e "s/{HIPAY_API_USER_TEST\}/$HIPAY_API_USER_RE7/" ./bin/docker/conf/acceptance/hipay.env.sample
    - sed -i -e "s/{HIPAY_API_PASSWORD_TEST\}/$HIPAY_API_PASSWORD_RE7/" ./bin/docker/conf/acceptance/hipay.env.sample
    - sed -i -e "s/{HIPAY_TOKENJS_PUBLICKEY_TEST\}/$HIPAY_TOKENJS_PUBLICKEY_RE7/" ./bin/docker/conf/acceptance/hipay.env.sample
    - sed -i -e "s/{HIPAY_TOKENJS_USERNAME_TEST\}/$HIPAY_TOKENJS_USERNAME_RE7/" ./bin/docker/conf/acceptance/hipay.env.sample
    - sed -i -e "s/{HIPAY_SECRET_PASSPHRASE_TEST\}/$HIPAY_SECRET_PASSPHRASE_RE7/" ./bin/docker/conf/acceptance/hipay.env.sample
    - sed -i -e "s/{HIPAY_API_USER_TEST_MOTO\}/$HIPAY_API_USER_TEST/" ./bin/docker/conf/acceptance/hipay.env.sample
    - sed -i -e "s/{HIPAY_API_PASSWORD_TEST_MOTO\}/$HIPAY_API_PASSWORD_TEST/" ./bin/docker/conf/acceptance/hipay.env.sample
    - sed -i -e "s/{HIPAY_SECRET_PASSPHRASE_TEST_MOTO\}/$HIPAY_SECRET_PASSPHRASE_TEST/" ./bin/docker/conf/acceptance/hipay.env.sample
    - sed -i -e "s@{PI_CI_DATA_URL\}@$PI_CI_DATA_URL@" ./bin/docker/conf/acceptance/hipay.env.sample
    - sed -i -e "s|\${DOCKER_STACK}|$DOCKER_STACK|g" docker-compose.acceptance.yml
    - sed -i -e "s|\${DOCKER_SERVICE}|$DOCKER_SERVICE|g" docker-compose.acceptance.yml
    - sed -i -e "s|\${CI_COMMIT_REF_SLUG}|$CI_COMMIT_REF_SLUG|g" docker-compose.acceptance.yml
    - sed -i -e "s|\${CI_JOB_ID}|$CI_JOB_ID|g" docker-compose.acceptance.yml
    - sed -i -e "s|\${REGISTRY_URL}|$REGISTRY_URL|g" docker-compose.acceptance.yml
    - sed -i -e "s|{MAGENTO_URL}|${DOCKER_STACK}-${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}.hipay-pos-platform.com|g" bin/docker/conf/acceptance/mage.env.sample
    - sed -i -e "s|{MYSQL_HOST}|${DOCKER_SERVICE}-${CI_JOB_ID}-database|g" bin/docker/conf/acceptance/mysql.env.sample
    # Change path for relative path to environment files
    - sed -i -e "s|./bin/docker/conf/acceptance/mysql.env.sample|mysql.env.sample|g" docker-compose.acceptance.yml
    - sed -i -e "s|./bin/docker/conf/acceptance/mage.env.sample|mage.env.sample|g" docker-compose.acceptance.yml
    - sed -i -e "s|./bin/docker/conf/acceptance/hipay.env.sample|hipay.env.sample|g" docker-compose.acceptance.yml
    # Push file on distant machine and launch deploy
    - bash /tools/deployToDockerMachine.sh -e ./bin/docker/conf/acceptance/hipay.env.sample -e ./bin/docker/conf/acceptance/mysql.env.sample -e ./bin/docker/conf/acceptance/mage.env.sample -s docker-compose.acceptance.yml -n $DOCKER_STACK-$DOCKER_SERVICE-$CI_COMMIT_REF_SLUG
  tags:
    - pi-commerce-no-overlay
  when: manual
  environment:
    name: review/${CI_COMMIT_REF_SLUG}
    url: https://${DOCKER_STACK}-${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}.hipay-pos-platform.com
  only:
    - branches
