image: $REGISTRY_CI/gitlab-ci-base:deployment

variables:
  GIT_DEPTH: 10

stages:
  - package

package:
  stage: package
  before_script:
    - apt-get install -y zip libapache2-mod-php php-curl php-xml
  script:
    - echo " Package module $CI_COMMIT_REF_SLUG"
    - cd src/lib/Hipay && composer install && cd ../../..
    - rm -Rf ./vendor && cp ./composer.json.dist ./composer.json && composer install &&  sh ./bin/deployment/packaging.sh
    - mkdir $CI_COMMIT_REF_SLUG
    - mkdir $CI_COMMIT_REF_SLUG/package
    - cp ./dist/*.tgz $CI_COMMIT_REF_SLUG/package/Allopass_Hipay-${CI_COMMIT_REF_SLUG}.tgz
  tags:
    - small
  artifacts:
    paths:
      - ./dist
