<?php
/**
 * HiPay Fullservice SDK Magento 1
 *
 * 2018 HiPay
 *
 * NOTICE OF LICENSE
 *
 * @author    HiPay <support.tpp@hipay.com>
 * @copyright 2018 HiPay
 * @license   https://github.com/hipay/hipay-fullservice-sdk-magento1/blob/master/LICENSE.md
 */
?>
<button type="button" class="scalable"
        onclick="if (confirm('<?php echo $this->getConfirmationMessage(); ?>')) {
            window.location='<?php echo $this->getButtonAction(); ?>'; return false; }"
        id="synchronize_button">
    <?php echo $this->escapeHtml($this->getLabel()); ?>
</button>
