<?php
/**
 * HiPay Fullservice SDK Magento 1
 *
 * 2018 HiPay
 *
 * NOTICE OF LICENSE
 *
 * @author    HiPay <support.tpp@hipay.com>
 * @copyright 2018 HiPay
 * @license   https://github.com/hipay/hipay-fullservice-sdk-magento1/blob/master/LICENSE.md
 */
?>
<?php
/**
 * @see Mage_Payment_Block_Info
 */
?>
<?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?>

<?php if ($_specificInfo = $this->getSpecificInformation()): ?>
    <table>
        <?php foreach ($_specificInfo as $_label => $_value): ?>
            <tr>
                <td><?php echo $this->escapeHtml($_label) ?>:</td>
                <td><?php echo nl2br(implode("\n", $this->getValueAsArray($_value, true))) ?></td>
            </tr>
        <?php endforeach ?>
    </table>
<?php endif ?>

<?php echo $this->getChildHtml() ?>
