<?php 
$_code=$this->getMethodCode();
$_cards = $this->getCards();

?>
<div id="payment_form_<?php echo $_code ?>" style="display:none;">
<?php if($this->allowSplitPayment()) : ?>
<ul class="form-list" id="splitpayment_card_payment_form_<?php echo $_code ?>" >
	 <li>
		 <div class="input-box">
		 	<label style="float: none;" for="<?php echo $_code ?>_split_payment"><?php echo $this->__('Split your Payment') ?></label><br />
		 	<select id="<?php echo $_code ?>_split_payment" name="payment[<?php echo $_code ?>_split_payment_id]">
		 		<!--  <option value=""><?php echo $this->__('-- Please select your split payment --')?></option> -->
		 		<?php foreach ($this->getSplitPaymentProfiles() as $profile) : ?>
		 			<option value="<?php echo $profile->getId()?>"><?php echo $profile->getName()?></option>
		 		<?php endforeach;?>
		 	</select>			
		 </div>
	 </li>
 </ul>
 <br />
<?php endif; ?>
<ul class="form-list" id="card_payment_form_<?php echo $_code ?>" >

 <li>
    <?php if(count($this->getCcAvailableTypes()) == 1) :?>
        	<label for="<?php echo $_code ?>_cc_type" ><?php echo $this->__('Credit Card Type') ?>: 
        		<?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
        				<?php echo $_typeName ?>
		                <input id="<?php echo $_code ?>_cc_type" value="<?php echo $_typeCode ?>" type="hidden" name="payment[<?php echo $_code ?>_cc_type]" />
		            <?php endforeach ?>
        	</label>
        <?php else:?>
	        <label for="<?php echo $_code ?>_cc_type"><?php echo $this->__('Credit Card Type') ?><span class="required">*</span></label>
	        <div class="input-box">
	        	
		            <select id="<?php echo $_code ?>_cc_type" name="payment[<?php echo $_code ?>_cc_type]" class="required-entry validate-cc-type-select">
		                <option value=""><?php echo $this->__('--Please Select--')?></option>
		            <?php $_ccType = $this->getInfoData('cc_type') ?>
		            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
		                <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
		            <?php endforeach ?>
	           
	            </select>
	        </div>
         <?php endif;?>
    </li>
    <?php if(Mage::getStoreConfigFlag('payment/'.$_code.'/display_card_owner')) : ?>
    <li>
        <label for="<?php echo $_code ?>_cc_owner"><?php echo $this->__('Name on Card') ?></label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" name="payment[<?php echo $_code ?>_cc_owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>" />
        </div>
    </li>
    <?php endif; ?>
    <li>
        <label for="<?php echo $_code ?>_cc_number" ><?php echo $this->__('Credit Card Number') ?><span class="required">*</span></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[<?php echo $_code ?>_cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="<?php echo $this->getInfoData('cc_number')?>" />
        </div>
    </li>
    <li id="<?php echo $_code ?>_cc_type_exp_div">
        <label for="<?php echo $_code ?>_expiration" ><?php echo $this->__('Expiration Date') ?><span class="required">*</span></label>
        <div class="input-box">
            <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration" name="payment[<?php echo $_code ?>_cc_exp_month]" class="month validate-cc-exp validate-cc-exp-split required-entry">
                <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" name="payment[<?php echo $_code ?>_cc_exp_year]" class="year required-entry">
                <?php foreach ($this->getCcYears() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <?php echo $this->getChildHtml() ?>
    <?php if($this->hasVerification()): ?>
    <li id="<?php echo $_code ?>_cc_type_cvv_div">
        <label for="<?php echo $_code ?>_cc_cid" ><?php echo $this->__('Card Verification Number') ?><span class="required">*</span></label>
        <div class="input-box">
            <div class="v-fix">
                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[<?php echo $_code ?>_cc_cid]" value="<?php echo trim($this->getInfoData('cc_cid'))?>" />
            </div>
            <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
        </div>
    </li>
    <?php endif; ?>

</ul>
<?php if ($this->oneClickIsAllowed()) : ?>
<ul class="form-list" id="oneclick_card_payment_form_<?php echo $_code ?>">
 <li>

			<?php if (!$this->getCustomerHasCard()) :?>
			<div class="input-box">
				<input id="<?php echo $_code ?>_create_alias_oneclick"  value="create_oneclick"  type="checkbox" name="payment[<?php echo $_code ?>_oneclick]" />
				<label style="float: none;" for="<?php echo $_code ?>_create_alias_oneclick"><?php echo $this->__('Save your card data for a next buy.') ?></label>
			</div>
		<?php else :?>
			<script type="text/javascript">$('card_payment_form_<?php echo $_code ?>').hide();</script>
			
			<div class="input-box">
				<input id="<?php echo $_code ?>_use_alias_oneclick" value="use_oneclick" checked="checked"   type="radio" name="payment[<?php echo $_code ?>_oneclick]" onclick="$('card_payment_form_<?php echo $_code ?>').hide();"   />
				<label style="float: none;" for="<?php echo $_code ?>_use_alias_oneclick"><?php echo $this->__('Use my saved card') ?></label>
			</div>
			
			<div class="input-box info-card">
				<select id="<?php echo $_code ?>_oneclick_selected_card" name="payment[<?php echo $_code ?>_oneclick_card]" >
					<?php foreach ($_cards as $card):?>
						<option value="<?php echo $card->getId()?>"><?php echo $card->getName()?></option>
					<?php endforeach;?>
			 	</select>
		 	</div>			
			
			<div class="input-box">
				<input id="<?php echo $_code ?>_create_alias_oneclick"  type="radio" name="payment[<?php echo $_code ?>_oneclick]" value="create_oneclick" onclick="$('card_payment_form_<?php echo $_code ?>').show();"/>
				<label style="float: none;" for="<?php echo $_code ?>_create_alias_oneclick"><?php echo $this->__('Save new card data') ?></label>
			</div>

			<div class="input-box">
				<input id="<?php echo $_code ?>_not_oneclick"  type="radio" name="payment[<?php echo $_code ?>_oneclick]" value="not_oneclick" onclick="$('card_payment_form_<?php echo $_code ?>').show();" />
				<label style="float: none;" for="<?php echo $_code ?>_not_oneclick"><?php echo $this->__('Do not use saved card data') ?></label>
			</div>

		<?php endif;?>
</li>
   
</ul>
 <br />
<script type="text/javascript">
 	//<![CDATA[

        var ToogleOneclick<?php echo $_code ?> = function() {
        	var elm = $('<?php echo $_code ?>_cc_type');
            if (['','VI','MC','AE'].indexOf(elm.value) != -1) {
                $('oneclick_card_payment_form_<?php echo $_code ?>').show();
            } else {
            	$('<?php echo $_code ?>_create_alias_oneclick').checked = false;
                $('oneclick_card_payment_form_<?php echo $_code ?>').hide();
            }
        };
        
        Event.observe($('<?php echo $_code ?>_cc_type'), 'change', ToogleOneclick<?php echo $_code ?>);
        document.observe("dom:loaded", function() {
        	 ToogleOneclick<?php echo $_code ?>();
        });
       
 	 //]]>
 </script>
 <?php endif; ?>

 <script type="text/javascript">
 	//<![CDATA[
 	    
 	    Validation.creditCartTypes.set('BCMC',[false, new RegExp('^([0-9]{3}|[0-9]{4})?$'), false]);
 	   Validation.creditCartTypes.set('CB',[new RegExp('^4[0-9]{12}([0-9]{3})?$'), new RegExp('^[0-9]{3}$'), true]);
        var ToogleCvn<?php echo $_code ?> = function() {
        	var elm = $('<?php echo $_code ?>_cc_type');
            if (['BCMC'].indexOf(elm.value) != -1) {
                $('<?php echo $_code ?>_cc_type_cvv_div').hide();
            } else {
                $('<?php echo $_code ?>_cc_type_cvv_div').show();
            }
        };
        
        Event.observe($('<?php echo $_code ?>_cc_type'), 'change', ToogleCvn<?php echo $_code ?>);
        ToogleCvn<?php echo $_code ?>();
        
 	 //]]>
 </script>
</div>

