<?php 
$_code=$this->getMethodCode();
$_cards = $this->getCards();
?>
<div id="payment_form_<?php echo $_code ?>" style="display:none;">
    <?php if (Mage::getStoreConfig('hipay/hipay_api_moto/moto_send_email')) {?>
        <?php echo $this->__('An email with a payment link will be sent to the customer.');?>
    <?php } ?>
<?php if($this->allowSplitPayment()) : ?>
<ul class="form-list" id="splitpayment_card_payment_form_<?php echo $_code ?>" >
	 <li>
		 <div class="input-box">
		 	<label style="float: none;" for="<?php echo $_code ?>_split_payment"><?php echo $this->__('Split your Payment') ?></label><br />
		 	<select id="<?php echo $_code ?>_split_payment" name="payment[<?php echo $_code ?>_split_payment_id]">
		 		<!-- <option value=""><?php echo $this->__('-- Please select your split payment --')?></option>  -->
		 		<?php foreach ($this->getSplitPaymentProfiles() as $profile) : ?>
		 			<option value="<?php echo $profile->getId()?>"><?php echo $profile->getName()?></option>
		 		<?php endforeach;?>
		 	</select>
		 </div>
	 </li>
 </ul>
 <br />
<?php endif; ?>
<?php if ($this->oneClickIsAllowed()) : ?>
<ul class="form-list" id="oneclick_hosted_payment_form_<?php echo $_code ?>">
 <li>

	<?php if (!$this->getCustomerHasCard()) :?>
			<div class="input-box">
				<input id="<?php echo $_code ?>_create_alias_oneclick"  value="create_oneclick"  type="checkbox" name="payment[<?php echo $_code ?>_oneclick]" />
				<label style="float: none;" for="<?php echo $_code ?>_create_alias_oneclick"><?php echo $this->__('Save your card data for a next buy.') ?></label>
			</div>
		<?php else :?>
			
			<div class="input-box">
				<input id="<?php echo $_code ?>_use_alias_oneclick" value="use_oneclick" checked="checked" type="radio" name="payment[<?php echo $_code ?>_oneclick]"  checked/>
				<label style="float: none;" for="<?php echo $_code ?>_use_alias_oneclick"><?php echo $this->__('Use my saved card') ?></label>
			</div>

			<div class="input-box info-card">
				<select id="<?php echo $_code ?>_oneclick_selected_card" name="payment[<?php echo $_code ?>_oneclick_card]" >
					<?php foreach ($_cards as $card):?>
						<option value="<?php echo $card->getId()?>"><?php echo $card->getName()?></option>
					<?php endforeach;?>
			 	</select>
		 	</div>
			
			<div class="input-box">
				<input id="<?php echo $_code ?>_create_alias_oneclick"  type="radio" name="payment[<?php echo $_code ?>_oneclick]" value="create_oneclick"/>
				<label style="float: none;" for="<?php echo $_code ?>_create_alias_oneclick"><?php echo $this->__('Save new card data') ?></label>
			</div>

			<div class="input-box">
				<input id="<?php echo $_code ?>_not_oneclick"  type="radio" name="payment[<?php echo $_code ?>_oneclick]" value="not_oneclick"  />
				<label style="float: none;" for="<?php echo $_code ?>_not_oneclick"><?php echo $this->__('Do not use saved card data') ?></label>
			</div>

		<?php endif;?>
</li>
   
</ul>
 <br />
 <?php endif; ?>
 </div>
