<?php

/**
 * HiPay Fullservice SDK Magento 1
 *
 * 2018 HiPay
 *
 * NOTICE OF LICENSE
 *
 * @author    HiPay <support.tpp@hipay.com>
 * @copyright 2018 HiPay
 * @license   https://github.com/hipay/hipay-fullservice-sdk-magento1/blob/master/LICENSE.md
 */

$_element = $this->getElement()
?>
<?php $_htmlId = $this->getHtmlId() ? $this->getHtmlId() : '_' . uniqid(); ?>
<?php $informations = $_element->getInformationsHipay(); ?>

<?php if (!empty($informations)) { ?>
    <div class="information-hipay" style="padding: 10px;">
        <div class="detail-information">
            <?php echo $informations ?>
        </div>
    </div>
<?php } ?>


