<?php

/**
 * HiPay Fullservice SDK Magento 1
 *
 * 2018 HiPay
 *
 * NOTICE OF LICENSE
 *
 * @author    HiPay <support.tpp@hipay.com>
 * @copyright 2018 HiPay
 * @license   https://github.com/hipay/hipay-fullservice-sdk-magento1/blob/master/LICENSE.md
 */

$_element = $this->getElement()
?>
<?php $_htmlId = $this->getHtmlId() ? $this->getHtmlId() : '_' . uniqid(); ?>
<input type="hidden" value="<?php echo $_element->getRule()->getId() ?>" name="<?php echo $_element->getName() ?>"/>
<div class="rule-tree">
    <div id="rule<?php echo $_htmlId ?>">
        <?php if ($_element->getRule() && $_element->getRule()->getConditions()) : ?>
            <?php echo $_element->getRule()->getConditions()->asHtmlRecursive(); ?>
        <?php endif; ?>
    </div>
</div>
<script type="text/javascript">
    var <?php  echo $_htmlId ?> =
    new VarienRulesForm('rule<?php echo $_htmlId ?>', '<?php echo $this->getNewChildUrl() ?>');
    <?php if ($_element->getReadonly()): ?>
    <?php echo $_htmlId ?>.setReadonly(true);
    <?php endif; ?>
</script>

