<?php 
$_code=$this->getMethodCode();
$_cards = $this->getCards();

?>
<div id="payment_form_<?php echo $_code ?>" style="display:none;">
<?php if($this->allowSplitPayment()) : ?>
<ul class="form-list" id="splitpayment_card_payment_form_<?php echo $_code ?>" >
	 <li>
		 <div class="input-box">
		 	<label style="float: none;" for="<?php echo $_code ?>_split_payment"><?php echo $this->__('Split your Payment') ?></label><br />
		 	<select id="<?php echo $_code ?>_split_payment" name="payment[<?php echo $_code ?>_split_payment_id]">
		 		<!--  <option value=""><?php echo $this->__('-- Please select your split payment --')?></option> -->
		 		<?php foreach ($this->getSplitPaymentProfiles() as $profile) : ?>
		 			<option value="<?php echo $profile->getId()?>"><?php echo $profile->getName()?></option>
		 		<?php endforeach;?>
		 	</select>			
		 </div>
	 </li>
 </ul>
 <br />
<?php endif; ?>
<?php if($_code != "hipay_sdd") : ?>
<ul class="form-list" id="card_payment_form_<?php echo $_code ?>" >

 <li>
    <?php if(count($this->getCcAvailableTypes()) == 1) :?>
        	<label for="<?php echo $_code ?>_cc_type" ><?php echo $this->__('Credit Card Type') ?>: 
        		<?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
        				<?php echo $_typeName ?>
		                <input id="<?php echo $_code ?>_cc_type" value="<?php echo $_typeCode ?>" type="hidden" name="payment[<?php echo $_code ?>_cc_type]" />
		            <?php endforeach ?>
        	</label>
        <?php else:?>
	        <label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
	        <div class="input-box">
	        	
		            <select id="<?php echo $_code ?>_cc_type" name="payment[<?php echo $_code ?>_cc_type]" class="required-entry validate-cc-type-select">
		                <option value=""><?php echo $this->__('--Please Select--')?></option>
		            <?php $_ccType = $this->getInfoData('cc_type') ?>
		            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
		                <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
		            <?php endforeach ?>
	           
	            </select>
	        </div>
         <?php endif;?>
    </li>
    <?php if(Mage::getStoreConfigFlag('payment/'.$_code.'/display_card_owner')) : ?>
    <li>
        <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" name="payment[<?php echo $_code ?>_cc_owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>" />
        </div>
    </li>
    <?php else: ?>
    	    <input type="hidden" id="<?php echo $_code ?>_cc_owner" name="payment[<?php echo $_code ?>_cc_owner]" value="<?php echo $this->htmlEscape($this->getQuote()->getBillingAddress()->getFirstname() . " " . $this->getQuote()->getBillingAddress()->getLastname()) ?>" />
    <?php endif; ?>
    <li>
        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[<?php echo $_code ?>_cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" />
        </div>
    </li>
    <li id="<?php echo $_code ?>_cc_type_exp_div">
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration" name="payment[<?php echo $_code ?>_cc_exp_month]" class="month validate-cc-exp validate-cc-exp-split required-entry">
                <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" name="payment[<?php echo $_code ?>_cc_exp_year]" class="year required-entry">
                <?php foreach ($this->getCcYears() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <?php echo $this->getChildHtml() ?>
    <?php if($this->hasVerification()): ?>
    <li id="<?php echo $_code ?>_cc_type_cvv_div">
        <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[<?php echo $_code ?>_cc_cid]" value="" />
            </div>
            <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
        </div>
    </li>
    <?php endif; ?>

</ul>
<?php if ($this->oneClickIsAllowed()) : ?>
<ul class="form-list" id="oneclick_card_payment_form_<?php echo $_code ?>">
 <li>

			<?php if (!$this->getCustomerHasCard()) :?>
			<div class="input-box">
				<input id="<?php echo $_code ?>_create_alias_oneclick"  value="create_oneclick"  type="checkbox" name="payment[<?php echo $_code ?>_oneclick]" />
				<label style="float: none;" for="<?php echo $_code ?>_create_alias_oneclick"><?php echo $this->__('Record your card data for a next buy.') ?></label>
			</div>
		<?php else :?>
			<script type="text/javascript">$('card_payment_form_<?php echo $_code ?>').hide();</script>
			
			<div class="input-box">
				<input id="<?php echo $_code ?>_use_alias_oneclick" value="use_oneclick" checked="checked"   type="radio" name="payment[<?php echo $_code ?>_oneclick]" onclick="$('card_payment_form_<?php echo $_code ?>').hide();"   />
				<label style="float: none;" for="<?php echo $_code ?>_use_alias_oneclick"><?php echo $this->__('Use my recorded card') ?></label>
			</div>
			
			<div class="input-box info-card">
				<select id="<?php echo $_code ?>_oneclick_selected_card" name="payment[<?php echo $_code ?>_oneclick_card]" >
					<?php foreach ($_cards as $card):?>
						<option value="<?php echo $card->getId()?>"><?php echo $card->getName()?></option>
					<?php endforeach;?>
			 	</select>
		 	</div>			
			
			<div class="input-box">
				<input id="<?php echo $_code ?>_create_alias_oneclick"  type="radio" name="payment[<?php echo $_code ?>_oneclick]" value="create_oneclick" onclick="$('card_payment_form_<?php echo $_code ?>').show();"/>
				<label style="float: none;" for="<?php echo $_code ?>_create_alias_oneclick"><?php echo $this->__('Record new card data') ?></label>
			</div>

			<div class="input-box">
				<input id="<?php echo $_code ?>_not_oneclick"  type="radio" name="payment[<?php echo $_code ?>_oneclick]" value="not_oneclick" onclick="$('card_payment_form_<?php echo $_code ?>').show();" />
				<label style="float: none;" for="<?php echo $_code ?>_not_oneclick"><?php echo $this->__('Not use record card data') ?></label>
			</div>

		<?php endif;?>
</li>
   
</ul>
 <br />
<script type="text/javascript">
 	//<![CDATA[

        var ToogleOneclick<?php echo $_code ?> = function() {
        	var elm = $('<?php echo $_code ?>_cc_type');
            if (['','VI','MC','AE'].indexOf(elm.value) != -1) {
                $('oneclick_card_payment_form_<?php echo $_code ?>').show();
            } else {
            	$('<?php echo $_code ?>_create_alias_oneclick').checked = false;
                $('oneclick_card_payment_form_<?php echo $_code ?>').hide();
            }
        };
        
        Event.observe($('<?php echo $_code ?>_cc_type'), 'change', ToogleOneclick<?php echo $_code ?>);
        document.observe("dom:loaded", function() {
        	 ToogleOneclick<?php echo $_code ?>();
        });
       
 	 //]]>
 </script>
 <?php endif; ?>
 <div id="<?php echo $_code ?>_debit_amount">
 <?php echo $this->__('You will be debit of amount %s only after submit order.',Mage::app()->getStore()->getBaseCurrency()->format($this->getQuote()->getGrandTotal(), array(), true))?>
 </div>
 <script type="text/javascript">
 	//<![CDATA[
 	    
 	    Validation.creditCartTypes.set('BCMC',[false, new RegExp('^([0-9]{3}|[0-9]{4})?$'), false]);
 	   Validation.creditCartTypes.set('CB',[new RegExp('^4[0-9]{12}([0-9]{3})?$'), new RegExp('^[0-9]{3}$'), true]);
 	        
        var ToogleCvn<?php echo $_code ?> = function() {
        	var elm = $('<?php echo $_code ?>_cc_type');
            if (['BCMC'].indexOf(elm.value) != -1) {
                $('<?php echo $_code ?>_cc_type_cvv_div').hide();
            } else {
                $('<?php echo $_code ?>_cc_type_cvv_div').show();
            }
        };
        
        Event.observe($('<?php echo $_code ?>_cc_type'), 'change', ToogleCvn<?php echo $_code ?>);
        ToogleCvn<?php echo $_code ?>();
        
        <?php if($this->allowSplitPayment()) : ?>
		var UpdateDebitAmount<?php echo $_code ?> = function(){
			
			new Ajax.Request('<?php echo Mage::getUrl('hipay/cc/updateDebitAmount',array('_secure'=>true)) ?>', {
	            evalScripts: true,
	            parameters: {'payment_profile_id': $('<?php echo $_code ?>_split_payment').value,'method_code': '<?php echo $_code ?>'},
	            onSuccess: function(transport) {
		            
	            	if (transport.responseText.isJSON()) {
	                    var response = transport.responseText.evalJSON();

	                    if (response.error) {
	                        $('<?php echo $_code ?>_debit_amount').innerHTML = response.message;
	                        Validation.add('validate-cc-exp-split', 'Incorrect credit card expiration date.', function(v,elm) {	                        	
	                            return true;
	                        });
							
	                    }

	                    if(response.success)
	                    {
		                    //Add validation for the last debit of split payments
	                    	var splitPayment = response.splitPayment;
							var dateArr = splitPayment[splitPayment.length - 1]['dateToPay'].split("-");

	                        Validation.add('validate-cc-exp-split', 'Incorrect credit card expiration date.', function(v,elm) {

	                        	var ccExpMonth   = v;
	                            var ccExpYear    = $(elm.id.substr(0,elm.id.indexOf('_expiration')) + '_expiration_yr').value;
	                            var currentTime  = new Date();
	                            var currentMonth = parseInt(dateArr[1]);//currentTime.getMonth() + 1;
	                            var currentYear  = parseInt(dateArr[0])//currentTime.getFullYear();
	                            
	                            if (ccExpMonth < currentMonth && ccExpYear == currentYear) {
	                                return false;
	                            }
	                            return true;
	                        });

	                        //Update HTMl
		                    $('<?php echo $_code ?>_debit_amount').innerHTML = response.labelSplitPayment;
		                    decorateTable('split-payment-cc-table')
		                    
	                    }
	            	}
		            
	                
	            }
	        });
			
		};

		Event.observe($('<?php echo $_code ?>_split_payment'), 'change', UpdateDebitAmount<?php echo $_code ?>);
		UpdateDebitAmount<?php echo $_code ?>();
        <?php endif; ?>
 	 //]]>
 </script>
<?php else : ?>
	<?php

	// TPPMAG1-2 - SEPA Payment.

	$useElectronicSigmature = Mage::getStoreConfig('payment/hipay_sdd/electronic_signature'); 
	?>
	<label for="<?php echo $_code ?>_type" ><?php echo $this->__('Bankwire method') ?>: 
		<?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
				<?php echo $_typeName ?>
                <input id="<?php echo $_code ?>_type" value="<?php echo $_typeCode ?>" type="hidden" name="payment[cc_type]" />
            <?php endforeach ?>
	</label>
	<?php if($useElectronicSigmature == 0) : ?>

	<ul class="form-list" id="card_payment_form_<?php echo $_code ?>" >
		<li>
			<label for="<?php echo $_code ?>_gender" class="required"><em>*</em><?php echo $this->__('Gender') ?></label>
	        <div class="input-box">
	            <select id="<?php echo $_code ?>_gender" name="payment[cc_gender]" >
					<option value="M" selected><?php echo $this->__('Male') ?></option>
					<option value="F"><?php echo $this->__('Female') ?></option>
			 	</select>
	        </div>
	    </li>
	    <li>
			<label for="<?php echo $_code ?>_fullname" class="required"><em>*</em><?php echo $this->__('firstname') ?></label>
	        <div class="input-box">
	            <input type="text" title="<?php echo $this->__('firstname') ?>" class="input-text " id="<?php echo $_code ?>_firstname" name="payment[cc_firstname]" value="<?php echo $this->htmlEscape(Mage::getSingleton('customer/session')->getCustomer()->getFirstname()); ?>" />
	        </div>
	    </li>
	    <li>
			<label for="<?php echo $_code ?>_fullname" class="required"><em>*</em><?php echo $this->__('lastname') ?></label>
	        <div class="input-box">
	            <input type="text" title="<?php echo $this->__('lastname') ?>" class="input-text " id="<?php echo $_code ?>_lastname" name="payment[cc_lastname]" value="<?php echo $this->htmlEscape(Mage::getSingleton('customer/session')->getCustomer()->getLastname()); ?>" />
	        </div>
	    </li>
		<li>
			<label for="<?php echo $_code ?>_iban" class="required"><em>*</em><?php echo $this->__('IBAN') ?></label>
	        <div class="input-box">
	            <input type="text" title="<?php echo $this->__('IBAN') ?>" class="input-text required-entry" id="<?php echo $_code ?>_iban" name="payment[cc_iban]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_iban')) ?>" />
	        </div>
	    </li>
	    <li>
			<label for="<?php echo $_code ?>_code_bic" class="required"><em>*</em><?php echo $this->__('Code BIC') ?></label>
	        <div class="input-box">
	            <input type="text" title="<?php echo $this->__('Code BIC') ?>" class="input-text required-entry" id="<?php echo $_code ?>_code_bic" name="payment[cc_code_bic]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_code_bic')) ?>" />
	        </div>
	    </li>
	    <li>
			<label for="<?php echo $_code ?>_bank_name" class="required"><em>*</em><?php echo $this->__('Bank name') ?></label>
	        <div class="input-box">
	            <input type="text" title="<?php echo $this->__('Bank name') ?>" class="input-text required-entry" id="<?php echo $_code ?>_bank_name" name="payment[cc_bank_name]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_bank_name')) ?>" />
	        </div>
	    </li>
   	</ul>
 	<?php endif; ?>
 	<div id="debit_amount">
	<?php echo $this->__('You will be debit of amount %s only after submit order.',Mage::app()->getStore()->getBaseCurrency()->format($this->getQuote()->getGrandTotal(), array(), true))?>
 	</div>
<?php endif; ?>

</div>

