<?php
/**
 * HiPay Fullservice SDK Magento 1
 *
 * 2018 HiPay
 *
 * NOTICE OF LICENSE
 *
 * @author    HiPay <support.tpp@hipay.com>
 * @copyright 2018 HiPay
 * @license   https://github.com/hipay/hipay-fullservice-sdk-magento1/blob/master/LICENSE.md
 */
?>
<?php
/** @var $this Allopass_Hipay_Block_Form_Abstract */
$_code = $this->getMethodCode();
$useOrderCurrency = Mage::getStoreConfig('hipay/hipay_api/currency_transaction', Mage::app()->getStore());
?>
<div id="payment_form_<?php echo $_code ?>" style="display:none;">
    <?php if ($this->allowSplitPayment()) : ?>
        <?php echo $this->getChildHtml('hipay_splitpayment'); ?>
    <?php endif; ?>
    <?php if (Mage::getStoreConfig('hipay/hipay_api/fingerprint', Mage::app()->getStore())) : ?>
        <?php echo $this->getChildHtml('hipay_fingerprint'); ?>
    <?php endif; ?>
    <?php if ($this->oneClickIsAllowed()) : ?>
        <?php echo $this->getChildHtml('hipay_oneclick'); ?>
    <?php endif; ?>
    <ul class="form-list" id="card_payment_form_<?php echo $_code ?>">
        <li>
            <?php if (count($this->getCcAvailableTypes()) == 1) : ?>
                <label for="<?php echo $_code ?>_cc_type"><?php echo $this->__('Credit Card Type') ?>:
                    <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                        <?php echo $_typeName ?>
                        <input id="<?php echo $_code ?>_cc_type" value="<?php echo $_typeCode ?>" type="hidden"
                               name="payment[<?php echo $_code ?>_cc_type]"/>
                    <?php endforeach ?>
                </label>
            <?php else: ?>
                <label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__(
                        'Credit Card Type'
                    ) ?></label>
                <div class="input-box">

                    <select id="<?php echo $_code ?>_cc_type" name="payment[<?php echo $_code ?>_cc_type]"
                            class="required-entry validate-cc-type-select">
                        <option value=""><?php echo $this->__('--Please Select--') ?></option>
                        <?php $_ccType = $this->getInfoData('cc_type') ?>
                        <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                            <option
                                    value="<?php echo $_typeCode ?>"<?php if ($_typeCode == $_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                        <?php endforeach ?>

                    </select>
                </div>
            <?php endif; ?>
        </li>
        <?php if (Mage::getStoreConfigFlag('payment/' . $_code . '/display_card_owner')) : ?>
            <li>
                <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__(
                        'Name on Card'
                    ) ?></label>
                <div class="input-box">
                    <input type="text" title="<?php echo $this->__('Name on Card') ?>"
                           class="input-text required-entry" id="<?php echo $_code ?>_cc_owner"
                           name="payment[<?php echo $_code ?>_cc_owner]"
                           value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>"/>
                </div>
            </li>
        <?php else: ?>
            <input type="hidden" id="<?php echo $_code ?>_cc_owner" name="payment[<?php echo $_code ?>_cc_owner]"
                   value="<?php echo $this->htmlEscape(
                       $this->getQuote()->getBillingAddress()->getFirstname() . " " . $this->getQuote()->getBillingAddress()->getLastname()
                   ) ?>"/>
        <?php endif; ?>
        <li>
            <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__(
                    'Credit Card Number'
                ) ?></label>
            <div class="input-box">
                <input type="text" id="<?php echo $_code ?>_cc_number"
                       name="payment[<?php echo $_code ?>_cc_number]"
                       title="<?php echo $this->__('Credit Card Number') ?>"
                       class="input-text validate-cc-number validate-cc-type" value=""/>
            </div>
        </li>
        <li id="<?php echo $_code ?>_cc_type_exp_div">
            <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__(
                    'Expiration Date'
                ) ?></label>
            <div class="input-box">
                <div class="v-fix">
                    <select id="<?php echo $_code ?>_expiration" name="payment[<?php echo $_code ?>_cc_exp_month]"
                            class="month validate-cc-exp validate-cc-exp-split required-entry">
                        <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                        <?php foreach ($this->getCcMonths() as $k => $v): ?>
                            <option
                                    value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
                <div class="v-fix">
                    <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                    <select id="<?php echo $_code ?>_expiration_yr" name="payment[<?php echo $_code ?>_cc_exp_year]"
                            class="year required-entry">
                        <?php foreach ($this->getCcYears() as $k => $v): ?>
                            <option
                                    value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>
        </li>
        <?php if ($this->hasVerification()): ?>
            <li id="<?php echo $_code ?>_cc_type_cvv_div">
                <label for="<?php echo $_code ?>_cc_cid" class="required"><em
                            id="<?php echo $_code ?>_cc_type_cvv_div_required">*</em><?php echo $this->__(
                        'Card Verification Number'
                    ) ?></label>
                <div class="input-box">
                    <div class="v-fix">
                        <input type="text" title="<?php echo $this->__('Card Verification Number') ?>"
                               class="input-text cvv required-entry validate-cc-cvn"
                               id="<?php echo $_code ?>_cc_cid" name="payment[<?php echo $_code ?>_cc_cid]"
                               value=""/>
                    </div>
                    <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
                </div>
            </li>
        <?php endif; ?>

    </ul>
    <div id="<?php echo $_code ?>_debit_amount">
        <?php if ($useOrderCurrency) { ?>
            <?php $this->getQuote()->setBaseCurrencyCode($this->getQuote()->getQuoteCurrencyCode()); ?>
            <?php echo $this->__(
                'You will be debited of %s only after submitting order.',
                Mage::app()->getStore()->getCurrentCurrency()->format(
                    $this->getQuote()->getGrandTotal(),
                    array(),
                    true
                )
            ) ?>
        <?php } else { ?>
            <?php echo $this->__(
                'You will be debited of %s only after submitting order.',
                Mage::app()->getStore()->getBaseCurrency()->format(
                    $this->getQuote()->getGrandTotal(),
                    array(),
                    true
                )
            ) ?>
        <?php } ?>
    </div>
    <script type="text/javascript">
        //<![CDATA[

        Validation.creditCartTypes.set('BCMC', [false, new RegExp('^([0-9]{3}|[0-9]{4})?$'), false]);
        Validation.creditCartTypes.set('CB', [new RegExp('^4[0-9]{12}([0-9]{3})?$'), new RegExp('^[0-9]{3}$'), true]);

        var ToogleCvn<?php echo $_code ?> = function () {
            var elm = $('<?php echo $_code ?>_cc_type');
            if (['BCMC'].indexOf(elm.value) != -1) {
                $('<?php echo $_code ?>_cc_type_cvv_div').hide();
            } else {
                $('<?php echo $_code ?>_cc_type_cvv_div').show();
                if (elm.value === "SM") {
                    $('<?php echo $_code ?>_cc_cid').removeClassName('required-entry');
                    $$('#<?php echo $_code ?>_cc_type_cvv_div label')[0].removeClassName('required');
                    $$('#<?php echo $_code ?>_cc_type_cvv_div label em')[0].hide();
                } else {
                    $('<?php echo $_code ?>_cc_cid').addClassName('required-entry');
                    $$('#<?php echo $_code ?>_cc_type_cvv_div label')[0].addClassName('required');
                    $$('#<?php echo $_code ?>_cc_type_cvv_div label em')[0].show();
                }
            }
        };

        Event.observe($('<?php echo $_code ?>_cc_type'), 'change', ToogleCvn<?php echo $_code ?>);
        ToogleCvn<?php echo $_code ?>();

        //]]>
    </script>

</div>

