<?php
/**
 * HiPay Fullservice SDK Magento 1
 *
 * 2018 HiPay
 *
 * NOTICE OF LICENSE
 *
 * @author    HiPay <support.tpp@hipay.com>
 * @copyright 2018 HiPay
 * @license   https://github.com/hipay/hipay-fullservice-sdk-magento1/blob/master/LICENSE.md
 */
?>
<?php
/** @var $this Allopass_Hipay_Block_Form_Abstract */
$_code = $this->getMethodCode();
$useOrderCurrency = Mage::getStoreConfig('hipay/hipay_api/currency_transaction', Mage::app()->getStore());
?>
<div id="payment_form_<?php echo $_code ?>" style="display:none;">
    <?php if ($this->allowSplitPayment()) : ?>
        <?php echo $this->getChildHtml('hipay_splitpayment'); ?>
    <?php endif; ?>
    <?php if (Mage::getStoreConfig('hipay/hipay_api/fingerprint', Mage::app()->getStore())) : ?>
        <?php echo $this->getChildHtml('hipay_fingerprint'); ?>
    <?php endif; ?>

    <!--[if IE 9]>
    <div class="ie9 hipayHF-container" id="hipayHF-container">
    <![endif]-->
    <!--[if gt IE 9]><!-->
    <div class="hipayHF-container" id="hipayHF-container">
        <!--<![endif]-->
        <div class="form-list" id="card_payment_form_<?php echo $_code ?>">
            <div class="hipayHF-row">
                <div class="hipayHF-field-container">
                    <div class="hipayHF-field" id="hipayHF-card-holder"></div>
                    <label class="hipayHF-label"
                           for="hipayHF-card-holder"><?php echo $this->__('Name on Card') ?></label>
                    <div class="hipayHF-baseline"></div>
                    <div class="hipay-field-error" data-hipay-id='hipay-card-field-error-cardHolder'></div>
                </div>
            </div>
            <div class="hipayHF-row">
                <div class="hipayHF-field-container">
                    <div class="hipayHF-field" id="hipayHF-card-number"></div>
                    <label class="hipayHF-label"
                           for="hipayHF-card-number"><?php echo $this->__('Credit Card Number') ?></label>
                    <div class="hipayHF-baseline"></div>
                    <div class="hipay-field-error" data-hipay-id='hipay-card-field-error-cardNumber'></div>
                </div>
            </div>
            <div class="hipayHF-row">
                <div class="hipayHF-field-container hipayHF-field-container-half">
                    <div class="hipayHF-field" id="hipayHF-date-expiry"></div>
                    <label class="hipayHF-label"
                           for="hipayHF-date-expiry"><?php echo $this->__('Expiry date') ?></label>
                    <div class="hipayHF-baseline"></div>
                    <div class="hipay-field-error" data-hipay-id='hipay-card-field-error-expiryDate'></div>
                </div>
                <div class="hipayHF-field-container hipayHF-field-container-half">
                    <div class="hipayHF-field" id="hipayHF-cvc"></div>
                    <label class="hipayHF-label"
                           for="hipayHF-cvc"><?php echo $this->__('Card Verification Number') ?></label>
                    <div class="hipayHF-baseline"></div>
                    <div class="hipay-field-error" data-hipay-id='hipay-card-field-error-cvc'></div>
                </div>
            </div>

            <div class="hipayHF-elements-container">
                <div id="hipayHF-help-cvc"></div>
            </div>
            <div id="hipayHF-error-message"></div>
        </div>
        <?php if ($this->oneClickIsAllowed()) : ?>
            <?php echo $this->getChildHtml('hipay_oneclick'); ?>
        <?php endif; ?>
    </div>

    <input type="hidden" value="" id="<?php echo $_code ?>_cc_owner" name="payment[<?php echo $_code ?>_cc_owner]">
    <input type="hidden" value="" id="<?php echo $_code ?>_cc_number"
           name="payment[<?php echo $_code ?>_cc_number]">
    <input type="hidden" value="" id="<?php echo $_code ?>_expiration"
           name="payment[<?php echo $_code ?>_cc_exp_month]">
    <input type="hidden" value="" id="<?php echo $_code ?>_expiration_yr"
           name="payment[<?php echo $_code ?>_cc_exp_year]">
    <input type="hidden" value="" id="<?php echo $_code ?>_cc_cid" name="payment[<?php echo $_code ?>_cc_cid]">
    <input type="hidden" value="" id="<?php echo $_code ?>_cc_type" name="payment[<?php echo $_code ?>_cc_type]">

    <div id="<?php echo $_code ?>_debit_amount">
        <?php if ($useOrderCurrency) { ?>
            <?php $this->getQuote()->setBaseCurrencyCode($this->getQuote()->getQuoteCurrencyCode()); ?>
            <?php echo $this->__(
                'You will be debited of %s only after submitting order.',
                Mage::app()->getStore()->getCurrentCurrency()->format(
                    $this->getQuote()->getGrandTotal(),
                    array(),
                    true
                )
            ) ?>
        <?php } else { ?>
            <?php echo $this->__(
                'You will be debited of %s only after submitting order.',
                Mage::app()->getStore()->getBaseCurrency()->format(
                    $this->getQuote()->getGrandTotal(),
                    array(),
                    true
                )
            ) ?>
        <?php } ?>
    </div>
    <input type="hidden" value="" id="<?php echo $_code ?>_browser_info" name="payment[<?php echo $_code ?>_browser_info]">
    <script type="text/javascript">
        //<![CDATA[

        var config = <?php echo $this->getConfigJson() ?>;
        var tokenizeEnv = 'production';
        var multiUse = false;
        var hfMethodCode = "<?php echo $_code ?>";

        if(config.isOneClick !== '0' || hfMethodCode === "hipay_hostedfieldsxtimes"){
            multiUse = true;
        }

        if (config.testMode == 1) {
            tokenizeEnv = 'stage'; // default is production/live
            config.api_tokenjs_username = config.api_tokenjs_username_test;
            config.api_tokenjs_publickey = config.api_tokenjs_publickey_test;
        }

        var hipay = HiPay({
            username: config.api_tokenjs_username,
            password: config.api_tokenjs_publickey,
            environment: tokenizeEnv,
            lang: config.lang
        });

        var config = {
            selector: "hipayHF-container",
            multi_use: multiUse,
            fields: {
                cardHolder: {
                    selector: "hipayHF-card-holder",
                    defaultFirstname: config.defaultFirstname,
                    defaultLastname: config.defaultLastname
                },
                cardNumber: {
                    selector: "hipayHF-card-number"
                },
                expiryDate: {
                    selector: "hipayHF-date-expiry"
                },
                cvc: {
                    selector: "hipayHF-cvc",
                    helpButton: true,
                    helpSelector: "hipayHF-help-cvc"
                }
            },
            styles: {
                base: config.style.base
            }
        };

        hipayHF = hipay.create("card", config);

        hipay.injectBaseStylesheet();

        hipayHF.on("blur", function (data) {
            // Get error container
            var domElement = document.querySelector(
                "[data-hipay-id='hipay-card-field-error-" + data.element + "']"
            );

            // Finish function if no error DOM element
            if (!domElement) {
                return;
            }

            // If not valid & not empty add error
            if (!data.validity.valid && !data.validity.empty) {
                domElement.innerText = data.validity.error;
            } else {
                domElement.innerText = '';
            }
        });

        hipayHF.on("inputChange", function (data) {
            // Get error container
            var domElement = document.querySelector(
                "[data-hipay-id='hipay-card-field-error-" + data.element + "']"
            );

            // Finish function if no error DOM element
            if (!domElement) {
                return;
            }

            // If not valid & not potentiallyValid add error (input is focused)
            if (!data.validity.valid && !data.validity.potentiallyValid) {
                domElement.innerText = data.validity.error;
            } else {
                domElement.innerText = '';
            }
        });

        function handleErrorHipayHF(valid, error) {
            document.getElementById("hipayHF-error-message").innerHTML = error;
        }

        $("ioBB").value = hipay.getDeviceFingerprint();
        $$('.ioBB_fingerprint').forEach(function (element) {
            element.value = hipay.getDeviceFingerprint();
        });

        if (hipay.getDeviceFingerprint() === undefined) {
            let retryCounter = 0;
            let interval = setInterval(function timeoutFunc() {
                retryCounter++;
                // If global_info init send event
                if (hipay.getDeviceFingerprint() !== undefined) {
                    $("ioBB").value = hipay.getDeviceFingerprint();
                    $$('.ioBB_fingerprint').forEach(function (element) {
                        element.value = hipay.getDeviceFingerprint();
                    });
                    clearInterval(interval);
                }
                // Max retry = 3
                if (retryCounter > 3) {
                    clearInterval(interval);
                }
            }, 1000);
        }

        //]]>
    </script>

</div>

