<?php
/**
 * HiPay Fullservice SDK Magento 1
 *
 * 2018 HiPay
 *
 * NOTICE OF LICENSE
 *
 * @author    HiPay <support.tpp@hipay.com>
 * @copyright 2018 HiPay
 * @license   https://github.com/hipay/hipay-fullservice-sdk-magento1/blob/master/LICENSE.md
 */
?>
<?php
$_code = $this->getMethodCode();
?>
<div id="payment_form_<?php echo $_code ?>" style="display:none;">
    <?php if ($this->allowSplitPayment()) : ?>
        <?php echo $this->getChildHtml('hipay_splitpayment'); ?>
    <?php endif; ?>
    <?php if (Mage::getStoreConfig('hipay/hipay_api/fingerprint', Mage::app()->getStore())) : ?>
        <?php echo $this->getChildHtml('hipay_fingerprint'); ?>
    <?php endif; ?>
    <?php if ($this->oneClickIsAllowed()) : ?>
        <?php echo $this->getChildHtml('hipay_oneclick'); ?>
    <?php endif; ?>
    <ul class="form-list" id="card_payment_form_<?php echo $_code ?>"></ul>
    <?php if ($this->allowSplitPayment()) : ?>
        <div id="<?php echo $_code ?>_debit_amount">
            <?php echo $this->__(
                'You will be debited of %s only after submitting order.',
                Mage::app()->getStore()->getBaseCurrency()->format(
                    $this->getQuote()->getGrandTotal(),
                    array(),
                    true
                )
            ) ?>
        </div>
    <?php endif; ?>
    <?php echo $this->__('You will be redirected to payment page after submitting order.') ?>
    <input type="hidden" value="" id="<?php echo $_code ?>_browser_info" name="payment[<?php echo $_code ?>_browser_info]">
    <script type="text/javascript">
        //<![CDATA[

        if(Review.prototype.iframeConfig === undefined){
            Review.prototype.iframeConfig = [];
        }

        <?php $iFrameConfig = $this->getIframeConfig() ?>

        Review.prototype.iframeConfig['<?php echo $_code;?>'] = JSON.parse('<?php echo json_encode($iFrameConfig);?>');


        Review.prototype.displayIframe = function (url, code) {

            // Create container Iframe
            var hipayIframeWrapper = $('hipay_iframe_wrapper');
            if (hipayIframeWrapper === null) {
                hipayIframeWrapper = new Element('div', {
                    id: 'hipay_iframe_wrapper',
                    style: Review.prototype.iframeConfig[code].iframe_wrapper_style
                });
                $('checkout-review-table-wrapper').insert({after: hipayIframeWrapper});

            }

            // generate Iframe
            hipayIframeWrapper.appendChild(new Element('iframe', {
                frameBorder: 0,
                width: Review.prototype.iframeConfig[code].iframe_width,
                height: Review.prototype.iframeConfig[code].iframe_height,
                src: url,
                style: Review.prototype.iframeConfig[code].iframe_style
            }));

        };

        Review.prototype.resetLoadWaiting = function (transport) {
            checkout.setLoadWaiting(false, this.isSuccess);
            if (transport && transport.responseText) {
                try {
                    response = eval('(' + transport.responseText + ')');
                }
                catch (e) {
                    response = {};
                }

                if (response.iframeUrl) {
                    $$('.btn-checkout')[0].hide();
                }
            }
        };

        Review.prototype.nextStep = function (transport) {
            if (transport && transport.responseText) {
                try {
                    response = eval('(' + transport.responseText + ')');
                }
                catch (e) {
                    response = {};
                }

                if (response.iframeUrl) {

                    this.displayIframe(response.iframeUrl, response.methodCode);
                    return;
                }

                if (response.redirect) {
                    this.isSuccess = true;
                    location.href = response.redirect;
                    return;
                }
                if (response.success) {
                    this.isSuccess = true;
                    window.location = this.successUrl;
                }
                else {
                    var msg = response.error_messages;
                    if (typeof(msg) == 'object') {
                        msg = msg.join("\n");
                    }
                    if (msg) {
                        alert(msg);
                    }
                }

                if (response.update_section) {
                    $('checkout-' + response.update_section.name + '-load').update(response.update_section.html);
                }

                if (response.goto_section) {
                    checkout.gotoSection(response.goto_section);
                }
            }
        };

        var config = <?php echo $this->getConfigJson() ?>;
        var tokenizeEnv = 'production';
        var multiUse = false;
        var hfMethodCode = "<?php echo $_code ?>";

        if(config.isOneClick !== '0' || hfMethodCode === "hipay_hostedfieldsxtimes"){
            multiUse = true;
        }

        if (config.testMode == 1) {
            tokenizeEnv = 'stage'; // default is production/live
            config.api_tokenjs_username = config.api_tokenjs_username_test;
            config.api_tokenjs_publickey = config.api_tokenjs_publickey_test;
        }

        var hipay = HiPay({
            username: config.api_tokenjs_username,
            password: config.api_tokenjs_publickey,
            environment: tokenizeEnv,
            lang: config.lang
        });

        document.getElementById(hfMethodCode + "_browser_info").value = JSON.stringify(hipay.getBrowserInfo());

        //]]>
    </script>
</div>
