<?php 
$_code=$this->getMethodCode();
$_cards = $this->getCards();
?>
<div id="payment_form_<?php echo $_code ?>" style="display:none;">
<?php if($this->allowSplitPayment()) : ?>
<ul class="form-list" id="splitpayment_card_payment_form_<?php echo $_code ?>" >
	 <li>
		 <div class="input-box">
		 	<label style="float: none;" for="<?php echo $_code ?>_split_payment"><?php echo $this->__('Split your Payment') ?></label><br />
		 	<select id="<?php echo $_code ?>_split_payment" name="payment[<?php echo $_code ?>_split_payment_id]">
		 		<!-- <option value=""><?php echo $this->__('-- Please select your split payment --')?></option>  -->
		 		<?php foreach ($this->getSplitPaymentProfiles() as $profile) : ?>
		 			<option value="<?php echo $profile->getId()?>"><?php echo $profile->getName()?></option>
		 		<?php endforeach;?>
		 	</select>
		 </div>
	 </li>
 </ul>
 <br />
<?php endif; ?>
<?php if ($this->oneClickIsAllowed()) : ?>
<ul class="form-list" id="oneclick_hosted_payment_form_<?php echo $_code ?>">
 <li>

	<?php if (!$this->getCustomerHasCard()) :?>
			<div class="input-box">
				<input id="<?php echo $_code ?>_create_alias_oneclick"  value="create_oneclick"  type="checkbox" name="payment[<?php echo $_code ?>_oneclick]" />
				<label style="float: none;" for="<?php echo $_code ?>_create_alias_oneclick"><?php echo $this->__('Save your card data for a next buy.') ?></label>
			</div>
		<?php else :?>
			
			<div class="input-box">
				<input id="<?php echo $_code ?>_use_alias_oneclick" value="use_oneclick" checked="checked" type="radio" name="payment[<?php echo $_code ?>_oneclick]"  checked/>
				<label style="float: none;" for="<?php echo $_code ?>_use_alias_oneclick"><?php echo $this->__('Use my saved card') ?></label>
			</div>

			<div class="input-box info-card">
				<select id="<?php echo $_code ?>_oneclick_selected_card" name="payment[<?php echo $_code ?>_oneclick_card]" >
					<?php foreach ($_cards as $card):?>
						<option value="<?php echo $card->getId()?>"><?php echo $card->getName()?></option>
					<?php endforeach;?>
			 	</select>
		 	</div>
			
			<div class="input-box">
				<input id="<?php echo $_code ?>_create_alias_oneclick"  type="radio" name="payment[<?php echo $_code ?>_oneclick]" value="create_oneclick"/>
				<label style="float: none;" for="<?php echo $_code ?>_create_alias_oneclick"><?php echo $this->__('Save new card data') ?></label>
			</div>

			<div class="input-box">
				<input id="<?php echo $_code ?>_not_oneclick"  type="radio" name="payment[<?php echo $_code ?>_oneclick]" value="not_oneclick"  />
				<label style="float: none;" for="<?php echo $_code ?>_not_oneclick"><?php echo $this->__('Do not use saved card data') ?></label>
			</div>

		<?php endif;?>
</li>
   
</ul>
 <br />
 <?php endif; ?>
 <?php if($this->allowSplitPayment()) : ?>
	 <div id="<?php echo $_code ?>_debit_amount">
	 <?php echo $this->__('You will be debited of %s only after submitting order.',Mage::app()->getStore()->getBaseCurrency()->format($this->getQuote()->getGrandTotal(), array(), true))?>
	 </div>
 <?php endif;?>
 <?php echo $this->__('You will be redirected to payment page after submitting order.')?>
<script type="text/javascript">
	//<![CDATA[
	
	<?php if($this->allowSplitPayment()) : ?>
	var UpdateDebitAmount<?php echo $_code ?> = function(){
			
			new Ajax.Request('<?php echo Mage::getUrl('hipay/hosted/updateDebitAmount',array('_secure'=>true)) ?>', {
	            evalScripts: true,
	            parameters: {'payment_profile_id': $('<?php echo $_code ?>_split_payment').value,'method_code': '<?php echo $_code ?>'},
	            onSuccess: function(transport) {
		            
	            	if (transport.responseText.isJSON()) {
	                    var response = transport.responseText.evalJSON();

	                    if (response.error) {
	                        $('<?php echo $_code ?>_debit_amount').innerHTML = response.message;	                        
							
	                    }

	                    if(response.success)
	                    {
	                        //Update HTMl
		                    $('<?php echo $_code ?>_debit_amount').innerHTML = response.labelSplitPayment;
		                    decorateTable('split-payment-cc-table')
		                    
	                    }
	            	}
		            
	                
	            }
	        });
			
		};

		Event.observe($('<?php echo $_code ?>_split_payment'), 'change', UpdateDebitAmount<?php echo $_code ?>);
		UpdateDebitAmount<?php echo $_code ?>();
	<?php endif; ?>
	
	<?php $iFrameConfig = $this->getIframeConfig() ?>
	
	Review.prototype.displayIframe = function(url) {
        
        
        
        // Create container Iframe
        var hipayIframeWrapper = $('hipay_iframe_wrapper');
        if (hipayIframeWrapper === null) {
            hipayIframeWrapper = new Element('div', {id: 'hipay_iframe_wrapper', style: '<?php echo $iFrameConfig['iframe_wrapper_style']?>'});
            $('checkout-review-table-wrapper').insert({after: hipayIframeWrapper});
            
        }

        // generate Iframe
        hipayIframeWrapper.appendChild(new Element('iframe', {frameBorder: 0, width: '<?php echo $iFrameConfig['iframe_width']?>', height: '<?php echo $iFrameConfig['iframe_height']?>', src: url, style: '<?php echo $iFrameConfig['iframe_style']?>'}));      

   };
   
   Review.prototype.resetLoadWaiting = function(transport){
        checkout.setLoadWaiting(false, this.isSuccess);
        if (transport && transport.responseText) {
	        	try{
	                response = eval('(' + transport.responseText + ')');
	            }
	            catch (e) {
	                response = {};
	            }
	            
	            if(response.iframeUrl)
            	{
            		$$('.btn-checkout')[0].hide();
            	}
        }
   };
	
	Review.prototype.nextStep = function(transport){
        if (transport && transport.responseText) {
            try{
                response = eval('(' + transport.responseText + ')');
            }
            catch (e) {
                response = {};
            }
            
            if(response.iframeUrl)
            {
            	
            	this.displayIframe(response.iframeUrl);         	
            	return;
            }
            
            if (response.redirect) {
                this.isSuccess = true;
                location.href = response.redirect;
                return;
            }
            if (response.success) {
                this.isSuccess = true;
                window.location=this.successUrl;
            }
            else{
                var msg = response.error_messages;
                if (typeof(msg)=='object') {
                    msg = msg.join("\n");
                }
                if (msg) {
                    alert(msg);
                }
            }

            if (response.update_section) {
                $('checkout-'+response.update_section.name+'-load').update(response.update_section.html);
            }

            if (response.goto_section) {
                checkout.gotoSection(response.goto_section);
            }
        }
	};
	
	
	 //]]>
</script>
 </div>
