<?php $_code=$this->getMethodCode() ?>
<div id="payment_form_<?php echo $_code ?>" style="display:none;">
<?php if ($this->oneClickIsAllowed()) : ?>
<ul class="form-list" id="oneclick_hosted_payment_form_<?php echo $_code ?>">
 <li>

			<?php if (!$this->getCustomerHasAlias() || ($this->getCustomerHasAlias() && !$this->ccExpDateIsValid())) :?>
			<div class="input-box">
				<input id="<?php echo $_code ?>_create_alias_oneclick"  value="create_oneclick"  type="checkbox" name="payment[oneclick]" />
				<label style="float: none;" for="<?php echo $_code ?>_create_alias_oneclick"><?php echo $this->__('Record your card data for a next buy.') ?></label>
			</div>
		<?php elseif ($this->getCustomerHasAlias() && $this->ccExpDateIsValid()): ?>
			<div class="input-box">
				<input id="<?php echo $_code ?>_use_alias_oneclick" value="use_oneclick" checked="checked"   type="radio" name="payment[oneclick]"   />
				<label style="float: none;" for="<?php echo $_code ?>_use_alias_oneclick"><?php echo $this->__('Use my recorded card') ?></label>
			</div>
			<div class="input-box info-card">
				<label><?php echo $this->__('Actual card') ?> :</label>
				<span><?php echo $this->getCustomer()->getHipayCcNumberEnc() ?></span>
			</div>
			<div class="input-box info-card">
				<label><?php echo $this->__('Expiration date') ?> : <?php echo $this->getCustomer()->getHipayCcExpDate() ?></label>
			</div>
			<div class="input-box">
				<input id="<?php echo $_code ?>_create_alias_oneclick"  type="radio" name="payment[oneclick]" value="create_oneclick"/>
				<label style="float: none;" for="<?php echo $_code ?>_create_alias_oneclick"><?php echo $this->__('Record new card data') ?></label>
			</div>

			<div class="input-box">
				<input id="<?php echo $_code ?>_not_oneclick"  type="radio" name="payment[oneclick]" value="not_oneclick"  />
				<label style="float: none;" for="<?php echo $_code ?>_not_oneclick"><?php echo $this->__('Not use record card data') ?></label>
			</div>

		<?php endif;?>
</li>
   
</ul>
 <?php endif; ?>
<?php echo $this->__('You will be redirect to payment page after submit order.')?>
<script type="text/javascript">
	//<![CDATA[
	
	Review.prototype.displayIframe = function(url) {
        
        
        
        // Create container Iframe
        var hipayIframeWrapper = $('hipay_iframe_wrapper');
        if (hipayIframeWrapper === null) {
            hipayIframeWrapper = new Element('div', {id: 'hipay_iframe_wrapper', style: 'text-align: center; border-bottom: 1px solid #BEBCB7; border-left: 1px solid #BEBCB7; border-right: 1px solid #BEBCB7;'});
            $('checkout-review-table-wrapper').insert({after: hipayIframeWrapper});
            
        }

        // generate Iframe
        hipayIframeWrapper.appendChild(new Element('iframe', {frameBorder: 0, width: '485px', height: '450px', src: url, style: 'margin: 10px 0; border: 1px solid #BEBCB7;'}));
        //var button = new Element('button', {'class': 'button', type: 'button'}).update('<span><span>Cancel</span></span>');
        //Event.observe(button, 'click', this.cancel.bind(this));
        //hipayIframeWrapper.appendChild(button);
        
        

   };
   
   Review.prototype.resetLoadWaiting = function(transport){
        checkout.setLoadWaiting(false, this.isSuccess);
        if (transport && transport.responseText) {
	        	try{
	                response = eval('(' + transport.responseText + ')');
	            }
	            catch (e) {
	                response = {};
	            }
	            
	            if(response.iframeUrl)
            	{
            		$$('.btn-checkout')[0].hide();
            	}
        }
   };
	
	Review.prototype.nextStep = function(transport){
        if (transport && transport.responseText) {
            try{
                response = eval('(' + transport.responseText + ')');
            }
            catch (e) {
                response = {};
            }
            
            if(response.iframeUrl)
            {
            	
            	this.displayIframe(response.iframeUrl);         	
            	return;
            }
            
            if (response.redirect) {
                this.isSuccess = true;
                location.href = response.redirect;
                return;
            }
            if (response.success) {
                this.isSuccess = true;
                window.location=this.successUrl;
            }
            else{
                var msg = response.error_messages;
                if (typeof(msg)=='object') {
                    msg = msg.join("\n");
                }
                if (msg) {
                    alert(msg);
                }
            }

            if (response.update_section) {
                $('checkout-'+response.update_section.name+'-load').update(response.update_section.html);
            }

            if (response.goto_section) {
                checkout.gotoSection(response.goto_section);
            }
        }
	};
	
	
	 //]]>
</script>
 </div>
