<div class="page-title">
    <h1><?php echo $this->__('Edit Card') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="form-validate">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo $this->__('Card %s',$this->htmlEscape($this->getCard()->getName())) ?></h2>
        <ul class="form-list">
            <li>
                <label for="name" class="required"><em>*</em><?php echo $this->__('Card Name') ?></label>
                <div class="input-box">
                    <input type="text" name="name" id="name" value="<?php echo $this->htmlEscape($this->getCard()->getName()) ?>" title="<?php echo $this->__('Card Name') ?>" class="input-text required-entry" />
                </div>
            </li>
            <li class="control">
                <input type="checkbox" name="is_default" id="is_default" value="<?php echo $this->getCard()->getIsDefault()?>" title="<?php echo $this->__('Is default') ?>"<?php if($this->getCard()->getIsDefault()==1): ?> checked="checked"<?php endif; ?> class="checkbox" />
                <label for="is_default"><?php echo $this->__('Is default') ?></label> 
           </li>
        </ul>
    </div>
    <div class="fieldset">
    	<ul class=forme-list>
    		<li><label><?php echo $this->__('Card Number') ?>: <?php echo $this->getCard()->getCcNumberEnc()?></label></li>
    		<li><label><?php echo $this->__('Exp. Date') ?>: <?php echo $this->getCard()->getCcExpMonth()?>/<?php echo $this->getCard()->getCcExpYear()?></label></li>
    	</ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>
</form>
